/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectGradlePratica05;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
    
    public String LibaryModified() {
    	return "fazendo mudancas";
    }
}
